### PR TITLE
Added the forms workshop repository

### PR DESCRIPTION
**Pull request by webmozart**
Fingers crossed that this is working :)

### CODE REVIEW

**Comment by emodric** [comment]
Thanks @webmozart!

But it didn't work completely :)

```
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                                 
  You have requested a non-existent parameter "database_path". Did you mean one of these: "database_host", "database_port", "database_name", "database_user"?
```

**Comment by webmozart** [comment]
Oops, result from a switch from SQLite to MySQL. Should be fixed now, could you try again?

**Comment by emodric** [comment]
Whoops, force push messes up the submodule, will fix and try again.

**Comment by emodric** [comment]
Next one:

```
Could not create database `forms` for connection named default
An exception occurred while executing 'CREATE DATABASE `forms`':

SQLSTATE[HY000]: General error: 1007 Can't create database 'forms'; database exists
```

Please, can you not use force push, it was a bitch to sort out :)

**Comment by webmozart** [comment]
What's your recommendation? Drop the database before?

**Comment by emodric** [comment]
It's empty, just skip the step where you create it? Is that an option?

Or use `CREATE DATABASE forms IF NOT EXISTS;` ?

**Comment by webmozart** [comment]
Ok, fixed.

**Comment by emodric** [comment]
Looks like it's working now, the app says I'm all alone :)

Thanks @webmozart !

**Comment by webmozart** [comment]
Great, thanks @emodric :)

**Pull request merged**
