### PR TITLE
Add the rabbit to setup.

### PR DESCRIPTION
**Pull request by vranac**
@emodric hopefully I got it right this time :)

### CODE REVIEW

**Comment by emodric** [comment]
Not quite :D

`workshops/rabittmq`

**Comment by vranac** [comment]
PEBKAC :D

**Comment by emodric** [comment]
Workshop folder still says rabitt :).

Btw, you don't need vhost?

**Comment by vranac** [comment]
@emodric if you already initialised, then yes, it will say the original faulty message.

No, I don't for now, but do leave the local domain setup as per document.

**Comment by vranac** [comment]
I'll have to close this pr (I'm awesome like that), and make things happen quick

**Comment by emodric** [comment]
I didn't, I'm on my phone, so I'm just looking at diff. Will test in an hour at the earliest.

Domain is already set up.

**Comment by emodric** [comment]
Can't you start from scratch and force push? No need for closing PRs then :)

**Pull request closed without merging**
